### ISSUE TITLE
streamline hinge recipe *suggestion*

### ISSUE THREAD

**Issue by Linkbro1** [Aetherial-Labs/HammersRingingFall#11]
there is no reason for top hinge flange and bottom hinge flange to be two separate recipes, sadly.

**Comment by VinterNacht** [comment]
https://s3.img-[b.com/image/private/t_base,c_lpad,f_auto,dpr_auto,w_330,h_320/v3/product/Deltana/deltana-dsb43-unl-7032587.jpg]

You can see the logic behind this decision here. One part of the hinge has three loops, the other two, with a pin going down the middle.

**Comment by Linkbro1** [comment]
i agree that it'd make logical sense, but sadly it doesn't seem like it works too well in game

**Comment by VinterNacht** [comment]
For what it's worth I'm likely to eliminate one of the two recipes and just make a hinge take two flanges and a pin.  rather than a top flange, bottom flange, and pin.

**Comment by VinterNacht** [comment]
Resolved in 1.2.2
