### ISSUE TITLE
4x Band recipe requires the use of unintended blacksmithing behavior in order to complete with a single ingot

### ISSUE THREAD

**Issue by Rosethorns** [Aetherial-Labs/HammersRingingFall#22]
The 4x band recipe is currently such that it can intuitively be attempted in two ways.
1. A single ingot in which you end up with 1 voxel missing and 3 unused voxels bridging the gaps between the 4 bands this ends in failure.
2. two ingots which completes the piece but wastes almost an entire extra ingot.

There is A way to complete the recipe with a single ingot but it uses unintended behavior with the blacksmithing mechanic which involves abusing the rules of when you can move a linking voxel resulting in a work piece that has seperate parts without being finished.

**Comment by VinterNacht** [comment]
This is functioning as intended. It is possible to finish the 4 band with a single ingot, with sufficient understanding of the smithing minigame.
