### ISSUE TITLE
recipe not working for metal spears :bug: 

### ISSUE THREAD

**Issue by matsaa93** [Aetherial-Labs/HammersRingingFall#6]
spear recipe is not right "game:spear-*"  while it should be "game:spearhead-*" in HammersRingingFall-*/assets/hammersringingfall/recipes/grid/metalspear.json 
it is hard to make a spear with a spear when you don't have one in the first place

**Comment by Linkbro1** [comment]
can confirm this, the recipe for a copper spear takes a copper spear when it should take a copper spearhead

**Comment by VinterNacht** [comment]
Resolved in 1.2.2
